apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployHamid40
  labels:
    app: autodeployHamid40
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719274146545
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployHamid40
  template:
    metadata:
      labels:
        app: autodeployHamid40
    spec:
      containers:
        - name: autodeployHamid40
          image: acrworkflow1719274146545.azurecr.io/image-workflow-1719274146545:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
