apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployhamid41
  labels:
    app: autodeployhamid41
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1719274791109
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployhamid41
  template:
    metadata:
      labels:
        app: autodeployhamid41
    spec:
      containers:
        - name: autodeployhamid41
          image: acrworkflow1719274791109.azurecr.io/image-workflow-1719274791109:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
