apiVersion: v1
kind: Service
metadata:
  name: autodeployHamid40
  namespace: namespace-workflow-1719274146545
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeployHamid40
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000