apiVersion: v1
kind: Service
metadata:
  name: autodeployhamid41
  namespace: namespace-workflow-1719274791109
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeployhamid41
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000